"""Markdown report generator."""
from __future__ import annotations
from arch_qube.rules.models import ScanReport


def generate_markdown(report: ScanReport) -> str:
    """Generate a human-readable Markdown report."""
    status = "PASS" if report.passed else "FAIL"
    emoji = "+" if report.passed else "x"
    lines = [
        f"# Architecture Qube Report",
        f"",
        f"**Framework:** {report.framework} | "
        f"**Files:** {report.files_scanned} | "
        f"**Score:** {report.total_score} / 100 ({report.grade}) | "
        f"**Status:** {status}",
        f"",
        f"## Rules",
        f"",
        f"| Rule | Severity | Compliance | Status |",
        f"|------|----------|------------|--------|",
    ]

    for r in sorted(report.rule_results, key=lambda x: x.compliance):
        status_mark = "PASS" if r.passed else "FAIL"
        lines.append(
            f"| {r.rule_name} | {r.severity.value} | "
            f"{r.compliance:.0f}% | {status_mark} |"
        )

    # Violations section
    if report.total_violations > 0:
        lines.extend([
            f"",
            f"## Violations ({report.total_violations} total)",
            f"",
        ])
        for r in report.rule_results:
            if not r.violations:
                continue
            lines.append(f"### {r.severity.value.upper()}: {r.rule_name}")
            for v in r.violations:
                lines.append(f"- `{v.file}:{v.line}` — {v.message}")
                if v.suggestion:
                    lines.append(f"  Fix: {v.suggestion}")
            lines.append("")

    lines.extend([
        "---",
        f"Generated by arch-qube v0.1.0",
    ])
    return "\n".join(lines)
